name: Vessel.js CI Workflow
on:
  push:
    paths-ignore:
      - "build/**"
    branches:
      - master
      - dev

  pull_request:
    paths-ignore:
      - "build/**"
    branches:
      - master
      - dev

permissions:
  contents: read

jobs:
  test:
    name: Test Vessel.js Code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust the Node.js version based on your project requirements

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: GIT commit and push
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
        run: |
          git add build
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
